user-id: 1
group-id: 1
volumes:
  /state: !Statedir {}
fileno-limit: 50ki
memory-limit: 2Gi
cpu-shares: 1024
workdir: /app
environ:
  TGDELETER_CONFIG: production_config.ProductionConfig

executable: /usr/bin/python3
arguments: [app.py]